#!/bin/sh

exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

set timeout=60
set gfxmode=3200x1800
terminal_output gfxterm

menuentry 'Remix OS' --class android-x86 {
        insmod part_gpt
        search --file --no-floppy --set=root /remix/system.img
        linux /remix/kernel root=/dev/ram0 androidboot.hardware=remix_x86_64 androidboot.selinux=permissive CMDLINE quiet DATA= CREATE_DATA_IMG=1 DPI=280
        initrd /remix/initrd.img
}

